---
- name: Installing vsftpd
  yum: name=vsftpd state=latest

- name: Start vsftpd
  service: name=vsftpd state=restarted

- name: Copying the configuration file
  template: src=vsftpd.conf.j2 dest=/etc/vsftpd/vsftpd.conf

- name: Uploading the file
  copy: dest=/var/ftp/pub/{{ filename }} src={{ filename }}
